
---------------------
----PROBLEM 1--------
---------------------
CREATE TABLE DEP_ACTIVE
AS
(
SELECT D.*,MAX(E.SALARY) MAX_SALARY FROM 
DEPARTMENTS D, EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID,D.DEPARTMENT_NAME,D.MANAGER_ID,D.LOCATION_ID
);


---------------------
----PROBLEM 2--------
---------------------
ALTER TABLE dep_active ADD CONSTRAINT dep_active_pk PRIMARY KEY (department_id);

ALTER TABLE dep_active
ADD CONSTRAINT fk_to_employees
FOREIGN KEY (manager_id)
REFERENCES employees(manager_id);

ALTER TABLE dep_active
MODIFY location_id int NOT NULL;

---------------------
----PROBLEM 3--------
---------------------
SELECT R.REGION_NAME, MAX(E.SALARY), MIN(E.SALARY)
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
JOIN COUNTRIES C ON (C.COUNTRY_ID = L.COUNTRY_ID)
FULL OUTER JOIN REGIONS R ON (R.REGION_ID = C .REGION_ID)
GROUP BY R.REGION_NAME;

---------------------
----PROBLEM 4--------
---------------------
SELECT L.CITY,SUM(SALARY) 
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON  (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
FULL OUTER JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
WHERE E.HIRE_DATE >= '01-JAN-1990' AND HIRE_DATE <= '31-DEC-1999'
GROUP BY L.CITY;

---------------------
----PROBLEM 5--------
---------------------

SELECT MAX(E.SALARY)   FROM EMPLOYEES E
JOIN EMPLOYEES DE ON E.EMPLOYEE_ID = DE.MANAGER_ID
JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
JOIN COUNTRIES C ON (C.COUNTRY_ID = L.COUNTRY_ID)
WHERE  E.SALARY > DE.SALARY
AND C.COUNTRY_NAME = 'UNITED STATES OF AMERICA';

---------------------
----PROBLEM 6--------
---------------------
SELECT EMP.LAST_NAME,  MAN.LAST_NAME
FROM  EMPLOYEES EMP JOIN EMPLOYEES MAN
ON  (EMP.MANAGER_ID = MAN.EMPLOYEE_ID)
WHERE ( EMP.HIRE_DATE < MAN.HIRE_DATE );

---------------------
----PROBLEM 7--------
---------------------
---------------------

---------------------
----PROBLEM 8--------
---------------------
SELECT D.DEPARTMENT_NAME, JOB_HIST.EMP_JOBHISTTABLE, EMP.EMPLOYEES_EMPTABLE
FROM
(
SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID) AS EMPLOYEES_EMPTABLE
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                        FROM DEPARTMENTS
                        WHERE LOCATION_ID IN (SELECT LOCATION_ID
                                                FROM LOCATIONS
                                                WHERE COUNTRY_ID = 'US'))
GROUP BY DEPARTMENT_ID
) EMP LEFT OUTER JOIN 
(SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID) AS EMP_JOBHISTTABLE
FROM JOB_HISTORY
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                        FROM DEPARTMENTS
                        WHERE LOCATION_ID IN (SELECT LOCATION_ID
                                                FROM LOCATIONS
                                                WHERE COUNTRY_ID = 'US'))
GROUP BY DEPARTMENT_ID
) JOB_HIST

ON EMP.DEPARTMENT_ID = JOB_HIST.DEPARTMENT_ID
LEFT OUTER JOIN DEPARTMENTS D
ON EMP.DEPARTMENT_ID = D.DEPARTMENT_ID;

---------------------
----PROBLEM 9--------
---------------------
SELECT E.LAST_NAME,COUNT(E.LAST_NAME)   FROM EMPLOYEES E
JOIN EMPLOYEES DE ON E.EMPLOYEE_ID = DE.MANAGER_ID GROUP BY E.LAST_NAME;


---------------------
----PROBLEM 10-------
---------------------
SELECT D.DEPARTMENT_ID, D.MANAGER_ID, L.LOCATION_ID
FROM DEPARTMENTS D,
LOCATIONS L
WHERE D.LOCATION_ID = L.LOCATION_ID
AND (D.DEPARTMENT_NAME LIKE '%A%' OR D.DEPARTMENT_NAME LIKE '%A%')
AND L.LOCATION_ID >=1500 AND L.LOCATION_ID <=1800;

---------------------
----PROBLEM 11-------
---------------------
SELECT E.LAST_NAME,R.REGION_NAME
FROM EMPLOYEES E
LEFT JOIN   DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
LEFT JOIN  LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
LEFT JOIN  COUNTRIES C ON (C.COUNTRY_ID = L.COUNTRY_ID)
LEFT JOIN  REGIONS R ON (R.REGION_ID = C .REGION_ID);


---------------------
----PROBLEM 12-------
---------------------
CREATE VIEW EMPLOYEEDETAILS AS 
SELECT EMPLOYEE.FIRST_NAME,EMPLOYEE.LAST_NAME,DEPARTMENT.DEPARTMENT_NAME
FROM EMPLOYEES EMPLOYEE JOIN DEPARTMENTS DEPARTMENT
ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
WITH READ ONLY;

SELECT * FROM EMPLOYEEDETAILS;
 
---------------------
----PROBLEM 13-------
---------------------
SELECT R.REGION_NAME, SUM(CASE WHEN E.SALARY > 5000 THEN 1 ELSE 0 END )  AS EMP_COUNT 
FROM REGIONS R
LEFT OUTER JOIN COUNTRIES C ON C.REGION_ID=R.REGION_ID
LEFT OUTER JOIN LOCATIONS L ON L.COUNTRY_ID=C.COUNTRY_ID
LEFT OUTER JOIN DEPARTMENTS D ON D.LOCATION_ID = L.LOCATION_ID
LEFT OUTER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY R.REGION_NAME
ORDER BY EMP_COUNT DESC;

---------------------
----PROBLEM 14-------
---------------------
SELECT B.MANAGER_ID,A.FIRST_NAME||' '||A.LAST_NAME AS "MANAGER'S NAME",A.SALARY
FROM EMPLOYEES A
RIGHT JOIN (SELECT MANAGER_ID FROM EMPLOYEES GROUP BY MANAGER_ID) B
ON A.EMPLOYEE_ID=B.MANAGER_ID
WHERE A.SALARY > (SELECT MAX(SALARY) AS SALARY
        FROM 
        (SELECT M.SALARY
        FROM EMPLOYEES M 
        LEFT OUTER JOIN EMPLOYEES E
        ON M.EMPLOYEE_ID = E.MANAGER_ID
        WHERE E.EMPLOYEE_ID IS NULL))
ORDER BY B.MANAGER_ID;

---------------------
----PROBLEM 15-------
---------------------

SELECT 
CASE WHEN SALARY>= 1000 AND SALARY <= 2999 THEN  'A'
WHEN SALARY>= 3000 AND SALARY <= 5999 THEN  'B'
WHEN SALARY>= 6000 AND SALARY <= 9999 THEN  'C'
WHEN SALARY>= 10000 AND SALARY <= 14999 THEN  'D'
WHEN SALARY>= 15000 AND SALARY <= 24999 THEN  'E'
WHEN SALARY>= 25000 AND SALARY <= 40000 THEN  'F'
END AS JOB_GRADE, COUNT(D.MANAGER_ID)
FROM EMPLOYEES E JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
GROUP BY CASE WHEN SALARY>= 1000 AND SALARY <= 2999 THEN  'A'
WHEN SALARY>= 3000 AND SALARY <= 5999 THEN  'B'
WHEN SALARY>= 6000 AND SALARY <= 9999 THEN  'C'
WHEN SALARY>= 10000 AND SALARY <= 14999 THEN  'D'
WHEN SALARY>= 15000 AND SALARY <= 24999 THEN  'E'
WHEN SALARY>= 25000 AND SALARY <= 40000 THEN  'F'
END;