---
title: "R Notebook"
author: "Anusha Karunakaran"
date: "09/19/2019"
output:
  html_document:
    df_print: paged
    toc: true
    theme: united
  html_notebook: default
  pdf_document: default
name: Anusha Karunakaran
---

# Problem 1

## Problem 1.a
<pre>
The events A and B are independent.
So, P(A ∩ B) = P(A) P(B). 
A ∩ B and A ∩ B’ are mutually exclusive and together they form the event A. 

A = ( A ∩ B) ∪ (A ∩ B’).
Also, 
P(A) = P[(A ∩ B) ∪ (A ∩ B’)]
P(A) = P(A ∩ B) + P(A ∩ B’)
P(A) = P(A) P(B) + P(A ∩ B’)
P(A ∩ B’) = P(A) − P(A) P(B) 
           = P(A) (1 – P(B)) 
           = P(A) P(B’)

From the above derivation it is proved that if A and B are independent events, then A and B' are also independent.

</pre>

<pre>
Example : 
A - Choosing a marble from a jar 
B - Landing on heads after tossing a coin

A and B are independent in the above events. 

Now, B' - Landing on tails after tossing a coin.
Events A and B' are still independent of each other.
</pre>

## Problem 1.b

### Problem a
The maximum value of P(A ∩ B) = min{P(A),P(B)} = 4/7

### Problem b
<b> P (A ∪ B) = P(A) + P(B) - P(A ∩ B) </b>
<pre>
Since, P(A∪B) ≤ 1  
2/3 + 4/7 - P(A ∩ B) ≤ 1
26/21 - P (A and B) ≤ 1

Min P(A and B) = 0.238
</pre>

### Problem c
The maximum value of P(A ∩ B') = min{P(A),P(B')} = 3/7

### Problem d

<pre>
Min[P(A and B')]= P(A) - Max[P(A and B)]
Min[P(A and B') = 0.67 - P(B)
Min[P(A and B') = 0.67 - 0.571
Min[P(A and B') = 0.099
</pre>

### Problem e 
<b> P(A ∪ B)= P(A) + P(B) - P(A ∩ B) </b> <br />
The maximum value of P(A ∪ B) is 1
    
### Problem f
<b> P(A  ∪ B)= P(A) + P(B) - P(A ∩ B) </b> <br />
<pre>
The minimum value of P(A ∪ B) = P(A) + P(B) - min{P(A),P(B)} <br />
                              = 2/3  + 4/7  - 4/7
                              = 2/3
</pre>
    
### Problem g
<b> P(A | B) = P(A ∩ B) / P(B) </b>  <br />
<pre>
The maximum value of P(A | B) is when P(A ∩ B) is maximum i.e min{P(A),P(B)} 
The maximum value of P(A | B) = min{P(A),P(B)} / P(B) 
                              = (4/7) / (4/7)
                              = 1
</pre>                            

### Problem h

<pre>
P(A | B) = min[P(A  ∩  B)] / P(B) 
         = 0.238/0.5714
         = 0.4165

The minimum value of P(A|B) = 0.4165      
</pre>

# Problem 2

<pre>
Let D be the event where the tested person has the disease 
Let E be the event where the test result is positive

According to the given values,
P(E|D) = 0.95 
P(E|D') = 0.01 
P(D) = 0.005
P(D') = 0.995 

Applying Bayes Rule,

P(D|E) = P(E|D). P(D) / {[P(E|D). P(D)] + [P(E|D'). P(D')]} 
       = 0.95 * 0.005 / {[0.95 * 0.005] + [0.995*0.001]} 
       = 0.3231 
       
The probability that the person has the disease given that his test result is positive is 0.3231.

</pre>


# Problem 3

## Problem 3.a
The probability that aircraft transmitter was made by Company A is 0.8.

## Problem 3.b

<pre>

P(A) = Aircraft manufactured by Company A  = 0.8 
P(B) = Aircraft manufactured by Company B  = 0.15 
P(C) = Aircraft manufactured by Company C  = 0.05 
P(D/A) = Defective percent by Company A = 0.03 
P(D/B) = Defective percent by Company B = 0.065
P(D/C) = Defective percent by Company C = 0.09 

P(A/D) = P(A). P(D/A) / {[P(A).P(D/A)] + [P(B).P(D/B)] + [P(B).P(D/B)]} 
       = (0.8*0.03)/{(0.8*0.03) + (0.15*0.065) + (0.05*0.09)
       = 0.627451

The probability that the randomly selected aircraft is tested and found to be defective by company A is 0.627451.

</pre>


# Problem 4

## Problem 4.a

<pre>

Sample Space = {(E1',E2',E3'),(E1',E2',E3),(E1',E2,E3'),(E1',E2,E3),(E1,E2',E3'),
(E1,E2',E3),(E1,E2,E3'),(E1,E2,E3)}

Total number of possibilities = 8

Events being successful  : P(E1) = P(E2) = P(E3) = 0.5
Events being unsuccessful: P(E1') = P(E2') = P(E3') = 0.5


Third event successful: (E1',E2',E3), (E1',E2,E3), (E1,E2',E3), (E1,E2,E3)

P(Third event successful) = Number of occurrences / Total number of possibilities
                          = 4/8
                          = 1/2
</pre>

## Problem 4.b

<pre>
P(A) = Third investment is successful
P(B) = All events are either successful or not successful

P(A ∩ B) = {(E1,E2,E3)}
P(B) = {(E1',E2',E3'),(E1,E2,E3)}

P(A|B) = P(A ∩ B) / P(B)
       = (1/8) / (2/8)
       =  1/2
</pre>

## Problem 4.c

<pre>
P(A) = Third investment is successful
P(B) = Two out of three investments are successful(Included the possibility where all three investments were successful)

 
P(A) = (E1',E2',E3), (E1',E2,E3), (E1,E2',E3), (E1,E2,E3)
P(B) = (E1',E2,E3), (E1,E2',E3), (E1,E2,E3'), (E1,E2,E3)

P(A ∩ B) = {(E1,E2',E3),(E1',E2,E3),(E1,E2,E3)}


P(A|B) = P(A ∩ B) / P(B)
       = (3/8) / (4/8)
       =  3/4
</pre>

## Problem 4.d

<pre>
P(E1) = Investment 1 is successful = 0.845
P(E2) = Investment 2 is successful = 0.5505
P(E3) = Investment 3 is successful = 0.4

P(E1') = Investment 1 is unsuccessful = 0.155
P(E2') = Investment 2 is unsuccessful = 0.4495
P(E3') = Investment 3 is unsuccessful = 0.6

A: Two of the three investments are successful
B: Investment 3 is successful.

P(A) : {(E1,E2,E3'),(E1,E2',E3),(E1',E2,E3)}
      =  0.845* 0.5505* 0.6 + 0.845* 0.4495 * 0.4 + 0.155 * 0.5505 * 0.4
      =  0.2791 + 0.1519 + 0.0341
      =  0.4651
P(B) = 0.4

P(A ∩ B) = (E1,E2',E3),(E1',E2,E3)
         = (0.845* 0.4495* 0.4) + (0.155* 0.5505* 0.4)
         = 0.1519 + 0.0341
         = 0.1860

P(A). P(B) = 0.4651 * 0.4
           = 0.1860
           

We observe that P(A ∩ B) = P(A). P(B) which implies that the events A and B are independent.
</pre>